blueprint:
  name: Randomized Offset Control (Supports Scenes - Fixed)
  description: >
    Activate lights/switches/scenes around sunrise, sunset, or fixed time with random ± offset.
    
    - Sunrise/Sunset: True ± variation (early trigger + random delay).
    - Fixed time: Set early trigger to base minus max offset.
    
    turn_on: Scenes → scene.turn_on; Lights/switches → light.turn_on (with optional brightness/transition).
    turn_off: Lights/switches only.
  domain: automation
  input:
    trigger_type:
      name: Trigger Type
      selector:
        select:
          options:
            - sunrise
            - sunset
            - fixed
      default: sunset
    max_offset_minutes:
      name: Max Random Offset (± minutes)
      default: 30
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    fixed_trigger_time:
      name: Early Trigger Time (Fixed only)
      selector:
        time:
    action:
      name: Action
      selector:
        select:
          options:
            - turn_on
            - turn_off
      default: turn_on
    entities:
      name: Entities/Scenes to Control
      description: Lights, switches, or scenes
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - scene
    brightness_pct:
      name: Brightness % (Lights turn_on only, optional)
      default: 0
      selector:
        number:
          min: 0
          max: 100
    transition:
      name: Transition Seconds (Lights turn_on only, optional)
      default: 0
      selector:
        number:
          min: 0
          max: 60

trigger:
  - platform: sun
    event: sunrise
    offset: "-{{ !input max_offset_minutes }}:00"
    id: sunrise
  - platform: sun
    event: sunset
    offset: "-{{ !input max_offset_minutes }}:00"
    id: sunset
  - platform: time
    at: !input fixed_trigger_time
    id: fixed

action:
  - variables:
      max_offset: !input max_offset_minutes
      has_scene: "{{ 'scene' in (entities.entity_id | map(attribute='domain') | unique | list) }}"
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunrise
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunrise' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunset
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunset' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: fixed
                  - condition: template
                    value_template: "{{ !input trigger_type == 'fixed' }}"
        sequence:
          - delay:
              seconds: "{{ range(0, (2 * max_offset * 60) + 1) | random }}"
          - choose:
              - conditions: "{{ !input action == 'turn_on' and has_scene }}"
                sequence:
                  - service: scene.turn_on
                    target: !input entities
              - conditions: "{{ !input action == 'turn_on' and not has_scene }}"
                sequence:
                  - choose:
                      - conditions: "{{ !input brightness_pct > 0 or !input transition > 0 }}"
                        sequence:
                          - service: light.turn_on
                            target: !input entities
                            data:
                              brightness_pct: "{{ !input brightness_pct if !input brightness_pct > 0 else none }}"
                              transition: "{{ !input transition if !input transition > 0 else none }}"
                      default:
                        - service: light.turn_on
                          target: !input entities
              - conditions: "{{ !input action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target: !input entities
    default: []

mode: single
