blueprint:
  name: Randomized Offset Control v1.8
  description: >
    v1.8 (Dec 2025) – Supports scenes, lights, switches. Random ± offset around sunrise/sunset/fixed time. Fixed all validation issues.
    
    • Sunrise/Sunset: true ± variation
    • Fixed time: set early trigger = base time minus max offset (e.g., want 18:30 ±30 → set 18:00)
    • turn_on: scenes → scene.turn_on | lights/switches → light.turn_on (with optional brightness/transition)
    • turn_off: lights/switches only
  domain: automation
  input:
    trigger_type:
      name: Trigger Type
      default: sunset
      selector:
        select:
          options:
            - sunrise
            - sunset
            - fixed
    max_offset_minutes:
      name: Max Random Offset (± minutes)
      default: 30
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    fixed_trigger_time:
      name: Early Trigger Time (only for Fixed)
      selector:
        time:
    action:
      name: Action
      default: turn_on
      selector:
        select:
          options:
            - turn_on
            - turn_off
    entities:
      name: Entities / Scenes to Control
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - scene
    brightness_pct:
      name: Brightness % (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 100
    transition:
      name: Transition seconds (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 60

trigger:
  - platform: sun
    event: sunrise
    offset: "-{{ max_offset_minutes }}:00"
    id: sunrise
  - platform: sun
    event: sunset
    offset: "-{{ max_offset_minutes }}:00"
    id: sunset
  - platform: time
    at: fixed_trigger_time
    id: fixed

action:
  - variables:
      is_turn_on: "{{ action == 'turn_on' }}"
      is_turn_off: "{{ action == 'turn_off' }}"
      target_dict: "{{ {'entity_id': entities.entity_id if entities.entity_id is iterable and entities.entity_id is not string else [entities.entity_id]} }}"
      has_scene: "{{ target_dict.entity_id | select('match', '^scene\\.') | list | count > 0 }}"
      has_params: "{{ brightness_pct > 0 or transition > 0 }}"
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunrise
                  - condition: template
                    value_template: "{{ trigger_type == 'sunrise' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunset
                  - condition: template
                    value_template: "{{ trigger_type == 'sunset' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: fixed
                  - condition: template
                    value_template: "{{ trigger_type == 'fixed' }}"
        sequence:
          - delay:
              seconds: "{{ range(0, (2 * max_offset_minutes * 60) + 1) | random }}"
          - choose:
              - conditions: "{{ is_turn_on and has_scene }}"
                sequence:
                  - service: scene.turn_on
                    target: "{{ target_dict }}"
          - choose:
              - conditions: "{{ is_turn_on and not has_scene and has_params }}"
                sequence:
                  - service: light.turn_on
                    target: "{{ target_dict }}"
                    data:
                      brightness_pct: brightness_pct
                      transition: transition
          - choose:
              - conditions: "{{ is_turn_on and not has_scene and not has_params }}"
                sequence:
                  - service: light.turn_on
                    target: "{{ target_dict }}"
          - choose:
              - conditions: "{{ is_turn_off }}"
                sequence:
                  - service: light.turn_off
                    target: "{{ target_dict }}"
    default: []
mode: single
