blueprint:
  name: Randomized Offset Control v1.4
  description: >
    v1.4 (Dec 2025) – Supports scenes, lights, switches. Random ± offset around sunrise/sunset/fixed time. Fully fixed validation errors.
    
    • Sunrise/Sunset: true ± variation
    • Fixed time: set early trigger = base time minus max offset (e.g., want 18:30 ±30 → set 18:00)
    • turn_on: scenes → scene.turn_on | lights/switches → light.turn_on (with optional brightness/transition)
    • turn_off: lights/switches only
  domain: automation
  input:
    trigger_type:
      name: Trigger Type
      default: sunset
      selector:
        select:
          options:
            - sunrise
            - sunset
            - fixed
    max_offset_minutes:
      name: Max Random Offset (± minutes)
      default: 30
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    fixed_trigger_time:
      name: Early Trigger Time (only for Fixed)
      selector:
        time:
    action:
      name: Action
      default: turn_on
      selector:
        select:
          options:
            - turn_on
            - turn_off
    entities:
      name: Entities / Scenes to Control
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - scene
    brightness_pct:
      name: Brightness % (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 100
    transition:
      name: Transition seconds (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 60

trigger:
  - platform: sun
    event: sunrise
    offset: "-{{ !input max_offset_minutes }}:00"
    id: sunrise
  - platform: sun
    event: sunset
    offset: "-{{ !input max_offset_minutes }}:00"
    id: sunset
  - platform: time
    at: !input fixed_trigger_time
    id: fixed

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunrise
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunrise' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunset
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunset' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: fixed
                  - condition: template
                    value_template: "{{ !input trigger_type == 'fixed' }}"
        sequence:
          - delay:
              seconds: "{{ range(0, (2 * !input max_offset_minutes * 60) + 1) | random }}"
          # Scene turn_on
          - choose:
              - conditions: "{{ !input action == 'turn_on' and 'scene' in (!input entities.entity_id | map(attribute='domain') | unique | list) }}"
                sequence:
                  - service: scene.turn_on
                    target: !input entities
          # Light/switch turn_on with brightness and/or transition
          - choose:
              - conditions: "{{ !input action == 'turn_on' and 'scene' not in (!input entities.entity_id | map(attribute='domain') | unique | list) and ( !input brightness_pct > 0 or !input transition > 0 ) }}"
                sequence:
                  - service: light.turn_on
                    target: !input entities
                    data:
                      brightness_pct: !input brightness_pct
                      transition: !input transition
          # Light/switch turn_on basic (no optional params)
          - choose:
              - conditions: "{{ !input action == 'turn_on' and 'scene' not in (!input entities.entity_id | map(attribute='domain') | unique | list) and !input brightness_pct == 0 and !input transition == 0 }}"
                sequence:
                  - service: light.turn_on
                    target: !input entities
          # turn_off
          - choose:
              - conditions: "{{ !input action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target: !input entities
    default: []
mode: single
