blueprint:
  name: Randomized Offset Control v8.2 (Fixed - No Offset Templates)
  description: >
    Supports scenes (turn_on only), lights, and switches. Random ± offset around sunrise/sunset or fixed time.
    • Symmetric random distribution centered on the target time
    • Separate inputs for scenes and devices to avoid service conflicts
    • Optional brightness and transition for lights
    • Works without templated sun offsets (HA limitation)
  domain: automation
  homeassistant:
    min_version: 2025.1.0
  input:
    trigger_type:
      name: Trigger Type
      default: sunset
      selector:
        select:
          options:
            - sunrise
            - sunset
            - fixed
    max_offset_minutes:
      name: Max Random Offset (± minutes)
      default: 30
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    fixed_trigger_time:
      name: Fixed Trigger Time (only used when Trigger Type = fixed)
      description: Time of day for the fixed trigger
      selector:
        time:
    action:
      name: Action
      default: turn_on
      selector:
        select:
          options:
            - turn_on
            - turn_off
    scene_targets:
      name: Scenes to Activate (turn_on only)
      description: Select one or more scene entities
      default: {}
      selector:
        target:
          entity:
            domain: scene
    device_targets:
      name: Lights / Switches to Control
      description: Lights and switches (brightness/transition apply to lights only)
      default: {}
      selector:
        target:
          entity:
            domain: [light, switch]
    brightness_pct:
      name: Brightness % (lights only, for turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    transition:
      name: Transition seconds (lights only, for turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

trigger:
  - platform: sun
    event: sunrise
    offset: 0
    id: sunrise
  - platform: sun
    event: sunset
    offset: 0
    id: sunset
  - platform: time
    at: !input fixed_trigger_time
    id: fixed

condition:
  - condition: template
    value_template: "{{ trigger.id == '!input trigger_type' }}"

action:
  - delay:
      seconds: "{{ range(0, ('!input max_offset_minutes' | int * 120) + 1) | random }}"
  - choose:
      - conditions: "{{ '!input action' == 'turn_on' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ '!input scene_targets'.entity_id | default([]) | length > 0 }}"
            then:
              - service: scene.turn_on
                data:
                  entity_id: "{{ '!input scene_targets'.entity_id }}"
          - if:
              - condition: template
                value_template: "{{ '!input device_targets'.entity_id | default([]) | length > 0 }}"
            then:
              - service: light.turn_on
                target: !input device_targets
                data: >
                  {% set bp = '!input brightness_pct' | int %}
                  {% set tr = '!input transition' | int %}
                  {% set parts = [] %}
                  {% if bp > 0 %}{% do parts.append('brightness_pct: ' ~ bp) %}{% endif %}
                  {% if tr > 0 %}{% do parts.append('transition: ' ~ tr) %}{% endif %}
                  {{ '{' ~ parts | join(', ') ~ '}' if parts else '{}' }}
      - conditions: "{{ '!input action' == 'turn_off' }}"
        sequence:
          - service: light.turn_off
            target: !input device_targets

mode: restart
max_exceeded: silent
