blueprint:
  name: Randomized Offset Control v5.0
  description: >
    v5.0 (Dec 2025) – Supports scenes, lights, switches. Random ± offset around sunrise/sunset/fixed time. Fixed delay validation.
    
    • Sunrise/Sunset: true ± variation (early offset + looped random delay)
    • Fixed time: early trigger + looped random delay
    • turn_on: scenes → scene.turn_on | lights/switches → light.turn_on (optional brightness/transition)
    • turn_off: lights/switches only
  domain: automation
  input:
    trigger_type:
      name: Trigger Type
      default: sunset
      selector:
        select:
          options:
            - sunrise
            - sunset
            - fixed
    max_offset_minutes:
      name: Max Random Offset (± minutes)
      default: 30
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    fixed_trigger_time:
      name: Early Trigger Time (only for Fixed)
      selector:
        time:
    action:
      name: Action
      default: turn_on
      selector:
        select:
          options:
            - turn_on
            - turn_off
    entities:
      name: Entities / Scenes to Control
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - scene
    brightness_pct:
      name: Brightness % (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 100
    transition:
      name: Transition seconds (lights only, turn_on)
      default: 0
      selector:
        number:
          min: 0
          max: 60

trigger:
  - platform: sun
    event: sunrise
    offset: "{{ max_offset_minutes * -60 }}"
    id: sunrise
  - platform: sun
    event: sunset
    offset: "{{ max_offset_minutes * -60 }}"
    id: sunset
  - platform: time
    at: !input fixed_trigger_time
    id: fixed

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunrise
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunrise' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: sunset
                  - condition: template
                    value_template: "{{ !input trigger_type == 'sunset' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: fixed
                  - condition: template
                    value_template: "{{ !input trigger_type == 'fixed' }}"
        sequence:
          - variables:
              full_minutes: "{{ !input max_offset_minutes }}"
              extra_minutes: "{{ !input max_offset_minutes }}"
              random_loops: "{{ range(0, full_minutes + 1) | random }}"
              random_seconds: "{{ range(0, 61) | random }}"
              entity_list: "{{ [entities.entity_id] if entities.entity_id is string else entities.entity_id }}"
              has_scene: "{{ entity_list | select('match', '^scene\\.') | list | count > 0 }}"
              has_params: "{{ !input brightness_pct > 0 or !input transition > 0 }}"
          - repeat:
              count: "{{ random_loops }}"
              sequence:
                - delay:
                    minutes: 1
          - delay:
              seconds: "{{ random_seconds }}"
          - if:
              - condition: template
                value_template: "{{ !input action == 'turn_on' and has_scene }}"
            then:
              - service: scene.turn_on
                target:
                  entity_id: "{{ entity_list }}"
          - if:
              - condition: template
                value_template: "{{ !input action == 'turn_on' and not has_scene and has_params }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: "{{ entity_list }}"
                data:
                  brightness_pct: !input brightness_pct
                  transition: !input transition
          - if:
              - condition: template
                value_template: "{{ !input action == 'turn_on' and not has_scene and not has_params }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: "{{ entity_list }}"
          - if:
              - condition: template
                value_template: "{{ !input action == 'turn_off' }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: "{{ entity_list }}"
    default: []
mode: single
